In [80]:
import pandas as pd
import numpy as np
#import spacy
import time
from tqdm import tqdm_notebook as tqdm
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer

In [81]:
df_items = pd.read_csv('items.csv')
df_cat= pd.read_csv('categories.csv')

In [82]:
df_items

       item_id  category_id                                          item_name
0            0           40             !! IN THE POWER OF HAPPINESS (PLAST) D
1            1           76  ! ABBYY FineReader 12 Professional Edition Ful...
2            2           40              *** IN THE GLORY OF THE GLORY (UNV) D
3            3           40                             *** BLUE WAVE (Univ) D
4            4           40                                  *** BOX (GLASS) D
...        ...          ...                                                ...
22165    22165           31             Nuclear Titbit 2 [PC, Digital Version]
22166    22166           54    Query language 1C: Enterprise [Digital version]
22167    22167           49  The query language is 1C: Enterprise 8 (+ CD)....
22168    22168           62                                 Egg for Little Inu
22169    22169           69                Egg of the Dragon (Game of Thrones)

[22170 rows x 3 columns]

In [83]:
df_cat

                 category_name  category_id
0   PC - Headsets / Headphones            0
1            Accessories - PS2            1
2            Accessories - PS3            2
3            Accessories - PS4            3
4            Accessories - PSP            4
..                         ...          ...
79                     Service           79
80           Service - Tickets           80
81         Blank media (spire)           81
82        Blank media (piece)            82
83                   Batteries           83

[84 rows x 2 columns]

In [84]:
#to select the categories
cat_name = df_cat['category_name']
cat_name

0     PC - Headsets / Headphones
1              Accessories - PS2
2              Accessories - PS3
3              Accessories - PS4
4              Accessories - PSP
                 ...
79                       Service
80             Service - Tickets
81           Blank media (spire)
82          Blank media (piece)
83                     Batteries
Name: category_name, Length: 84, dtype: object

In [85]:
cat_name.apply(lambda x: x.split("-")[0])

0                       PC
1              Accessories
2              Accessories
3              Accessories
4              Accessories
              ...
79                  Service
80                 Service
81      Blank media (spire)
82     Blank media (piece)
83                Batteries
Name: category_name, Length: 84, dtype: object

In [86]:
item_name = df_items['item_name']
item_name

0                   !! IN THE POWER OF HAPPINESS (PLAST) D
1        ! ABBYY FineReader 12 Professional Edition Ful...
2                    *** IN THE GLORY OF THE GLORY (UNV) D
3                                   *** BLUE WAVE (Univ) D
4                                        *** BOX (GLASS) D
                               ...
22165               Nuclear Titbit 2 [PC, Digital Version]
22166      Query language 1C: Enterprise [Digital version]
22167    The query language is 1C: Enterprise 8 (+ CD)....
22168                                   Egg for Little Inu
22169                  Egg of the Dragon (Game of Thrones)
Name: item_name, Length: 22170, dtype: object

In [87]:
bow = CountVectorizer(min_df =0.1)
item_name_bow = bow.fit_transform(item_name)
tokens = bow.get_feature_names()
pd.DataFrame(data=item_name_bow.toarray(),columns=tokens)

       of  pc  the  version
0       1   0    1        0
1       0   1    0        1
2       1   0    2        0
3       0   0    0        0
4       0   0    0        0
...    ..  ..  ...      ...
22165   0   1    0        1
22166   0   0    0        1
22167   0   0    1        0
22168   0   0    0        0
22169   2   0    1        0

[22170 rows x 4 columns]

In [88]:
bow = CountVectorizer(ngram_range=(1, 2), min_df=0.01)
item_name_bow = bow.fit_transform(item_name)
tokens = bow.get_feature_names()
pd.DataFrame(data=item_name_bow.toarray(),columns=tokens)

,1c,1c audiobooks,2cd,360,360 russian,3d,3d bd,and,art,assassin,...,time,to,toy,version,war,with,world,xbox,xbox 360,year
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22165,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
22166,1,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
22167,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
22168,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
22169,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [89]:
bow = CountVectorizer(ngram_range=(2, 2), min_df=0.01)
item_name_bow = bow.fit_transform(item_name)
tokens = bow.get_feature_names()
pd.DataFrame(data=item_name_bow.toarray(),columns=tokens)

,1c audiobooks,360 russian,3d bd,assassin creed,board game,cd digipack,cd jewel,digital version,edition pc,english version,...,of the,pc digital,pc jewel,pc russian,ps3 russian,russian documentation,russian subtitles,russian version,soft toy,xbox 360
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,1,0,0,...,0,1,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22165,0,0,0,0,0,0,0,1,0,0,...,0,1,0,0,0,0,0,0,0,0
22166,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
22167,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
22168,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
22169,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0

In [93]:
tfidf = TfidfVectorizer(min_df = 0.01)
item_name_tfidf = tfidf.fit_transform(item_name)
tokens = tfidf.get_feature_names()
pd.DataFrame(data=item_name_tfidf.toarray(),columns=tokens)

,1c,2cd,360,3d,and,art,assassin,audiobooks,bd,best,...,the,time,to,toy,version,war,with,world,xbox,year
0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.472517,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0
1,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.418051,0.0,0.0,0.0,0.0,0.0
2,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.731329,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0
3,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0
4,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22165,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.525248,0.0,0.0,0.0,0.0,0.0
22166,0.678516,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.470353,0.0,0.0,0.0,0.0,0.0
22167,0.637971,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.424244,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0
22168,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0
22169,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.350743,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0

In [95]:
tfidf = TfidfVectorizer(ngram_range=(1, 2), min_df=0.01)
item_name_tfidf = tfidf.fit_transform(item_name)
tokens = tfidf.get_feature_names()
pd.DataFrame(data=item_name_tfidf.toarray(),columns=tokens)

,1c,1c audiobooks,2cd,360,360 russian,3d,3d bd,and,art,assassin,...,time,to,toy,version,war,with,world,xbox,xbox 360,year
0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
1,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.338186,0.0,0.0,0.0,0.0,0.0,0.0
2,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
3,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
4,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22165,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.387890,0.0,0.0,0.0,0.0,0.0,0.0
22166,0.589815,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.408865,0.0,0.0,0.0,0.0,0.0,0.0
22167,0.637971,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
22168,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
22169,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0

In [96]:
tfidf = TfidfVectorizer(ngram_range=(2, 2), min_df=0.01)
item_name_tfidf = tfidf.fit_transform(item_name)
tokens = tfidf.get_feature_names()
pd.DataFrame(data=item_name_tfidf.toarray(),columns=tokens)

,1c audiobooks,360 russian,3d bd,assassin creed,board game,cd digipack,cd jewel,digital version,edition pc,english version,...,of the,pc digital,pc jewel,pc russian,ps3 russian,russian documentation,russian subtitles,russian version,soft toy,xbox 360
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,...,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.695536,0.0,0.0,...,0.000000,0.718491,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,...,0.603988,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,...,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,...,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22165,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.695536,0.0,0.0,...,0.000000,0.718491,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
22166,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.000000,0.0,0.0,...,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
22167,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,...,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
22168,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,...,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
22169,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,...,1.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0